---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-demo
spec:
  selector:
    matchLabels:
      app: container-demo
  template:
    metadata:
      labels:
        app: container-demo
    spec:
      containers:
      - name: container-demo
        image: ghcr.io/middlewaregruppen/container-demo:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: container-demo
spec:
  type: LoadBalancer
  selector:
    app: container-demo
  ports:
  - port: 80
    targetPort: 8080